### ISSUE TITLE
Potential issues during installation (and how to resolve them)

### ISSUE THREAD

**Issue by Yasu31** [srl-ethz/faive_gym_oss#3]
**please keep this thread open**
List of issues encountered during installation of faive_gym (and the libraries it depends on), and how it was resolved. If it's an issue that many encounter, consider creating a PR to modify the README of the repository itself.

## template
```markdown
## Issue Description
Please describe the issue you encountered during the installation of faive_gym and its dependent libraries. Include any error messages and the steps leading up to the issue.

## (Attempted) Solutions
Describe any solutions or troubleshooting steps you've attempted.

## Screenshots
If applicable, add screenshots to help explain your problem.
```

**Comment by Yasu31** [comment]
## Issue Description
Issue with np.float being deprecated with **AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`.** 
```
Traceback (most recent call last):
  File "train.py", line 81, in launch_rlg_hydra
    from isaacgymenvs.utils.rlgames_utils import multi_gpu_get_rank
  File "/home/ubuntu/git/IsaacGymEnvs/isaacgymenvs/utils/rlgames_utils.py", line 40, in <module>
    from isaacgymenvs.tasks import isaacgym_task_map
  File "/home/ubuntu/git/IsaacGymEnvs/isaacgymenvs/tasks/__init__.py", line 56, in <module>
    from .industreal.industreal_task_pegs_insert import IndustRealTaskPegsInsert
  File "/home/ubuntu/git/IsaacGymEnvs/isaacgymenvs/tasks/industreal/industreal_task_pegs_insert.py", line 46, in <module>
    from isaacgym import gymapi, gymtorch, torch_utils
  File "/home/ubuntu/Downloads/isaacgym/python/isaacgym/torch_utils.py", line 135, in <module>
    def get_axis_params(value, axis_idx, x_value=0., dtype=np.float, n_dims=3):
  File "/home/ubuntu/anaconda3/envs/Faive/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

## Solutions
Change np.float →float in the isaacgym/torch_utils.py file

**Comment by Yasu31** [comment]
## Issue Description
`import tkinter` fails, even though `sudo apt install python3-tk` was run

## Solutions
Had to run `sudo apt install python3.8-tk` instead of `sudo apt install python3-tk`

**Comment by Yasu31** [comment]
## Issue Description
error about np.int being deprecated comes up from the networkx package

## Solutions
specify a newer version of networkx, with `pip install networkx==3.1`

**Comment by Yasu31** [comment]
## Issue Description
Installation of IsaacGymEnvs fails due to `pysdf` failing to install
```
  Running setup.py install for pysdf ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pysdf did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Couldn't find Eigen locally, downloading...
      Found eigen at eigen-3.3.7
      /home/yasu/rlgpu/lib/python3.8/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      WARNING: The wheel package is not available.
      running install
      running build
      running build_ext
      creating tmp
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yasu/rlgpu/include -I/usr/include/python3.8 -c /tmp/tmpl4211qns.cpp -o tmp/tmpl4211qns.o -std=c++17
      unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yasu/rlgpu/include -I/usr/include/python3.8 -c /tmp/tmp9mpbaq5q.cpp -o tmp/tmp9mpbaq5q.o -std=c++14
      unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yasu/rlgpu/include -I/usr/include/python3.8 -c /tmp/tmpt8vlkwzn.cpp -o tmp/tmpt8vlkwzn.o -std=c++11
      unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vadqclh2/pysdf_710e86485be94920b457904aed5a063a/setup.py", line 186, in <module>
          setup(
        File "/home/yasu/rlgpu/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/yasu/rlgpu/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
          self.run_command('build')
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/yasu/rlgpu/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-vadqclh2/pysdf_710e86485be94920b457904aed5a063a/setup.py", line 172, in build_extensions
          opts.append(cpp_flag(self.compiler))
        File "/tmp/pip-install-vadqclh2/pysdf_710e86485be94920b457904aed5a063a/setup.py", line 147, in cpp_flag
          raise RuntimeError('Unsupported compiler -- at least C++11 support '
      RuntimeError: Unsupported compiler -- at least C++11 support is needed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pysdf

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip is available: 23.0.1 -> 24.0
```

## (Attempted) Solutions
As it was implied that C++ support was needed, installed `sudo apt install build-essential` which fixed the problem.
